schema = 3

[mod]
  [mod."github.com/alecthomas/kong"]
    version = "v1.13.0"
    hash = "sha256-9nSlldkif002WKjCIRBUmTofdtSL16V9NUZZ1PD34c0="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.11.5"
    hash = "sha256-jN5+2ED+YbIoPIuyJ4Ou5pqJb2w1uNKzp5yTjKY6rEQ="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/ghodss/yaml"]
    version = "v1.0.0"
    hash = "sha256-D+2i+EwF2YptR0m/OG4WIVVLL7tUC7XvgRQef2usfGo="
  [mod."github.com/go-faster/errors"]
    version = "v0.7.1"
    hash = "sha256-X+Yp7AiTfEQ0kOoixqOud8nN3XvfGLLB/ijXZ+SXhvc="
  [mod."github.com/go-faster/jx"]
    version = "v1.2.0"
    hash = "sha256-6QcSzvIM0JbtmaJxwc6RMOVPh8THotZl54ZaBKDDRpM="
  [mod."github.com/go-faster/yaml"]
    version = "v0.4.6"
    hash = "sha256-SCkpp6y41egb/zCW/hMIJlM/QNYS4LBw5YaK1Avz0YM="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/ogen-go/ogen"]
    version = "v1.18.0"
    hash = "sha256-uq3fxr8z+rXUQAW+BSO2QyBGJP7KrFKFBAFxtTz3gjM="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/r3labs/diff/v3"]
    version = "v3.0.2"
    hash = "sha256-oor5U5ClSXfR30JB15JxQINjFLMNoi9ZXjjARC8A3P0="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.1"
    hash = "sha256-XhAJObkSa7gjx3PqYrreVEcMHBc/rDVeY/lWvNccGB0="
  [mod."github.com/shopspring/decimal"]
    version = "v1.4.0"
    hash = "sha256-U36bC271jQsjuWFF8BfLz4WicxPJUcPHRGxLvTz4Mdw="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/vmihailenco/msgpack/v5"]
    version = "v5.4.1"
    hash = "sha256-pDplX6xU6UpNLcFbO1pRREW5vCnSPvSU+ojAwFDv3Hk="
  [mod."github.com/vmihailenco/tagparser/v2"]
    version = "v2.0.0"
    hash = "sha256-M9QyaKhSmmYwsJk7gkjtqu9PuiqZHSmTkous8VWkWY0="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.39.0"
    hash = "sha256-ExtTq4iRL2Hsh9CIPudao86Y1qtisRzIIzaH7QngEIU="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.39.0"
    hash = "sha256-VbkFRo307Sicjk3DKOkim8ptLZafAiK3vUMQdyusxF4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.39.0"
    hash = "sha256-5e2yJbiJPcuXq5ldOA8Z4hHIh4Ywk0MgQ9OHNqOAiRo="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.1"
    hash = "sha256-bn/MMu7X3GkUuW12Xwn9JYbOJeEu9+yoQtkmO+36xlQ="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230725093048-515e97ebf090"
    hash = "sha256-MynD8x+mg/OAZGFcrN89I243j+b29bzmqTYHZeIs87I="
  [mod."golang.org/x/net"]
    version = "v0.47.0"
    hash = "sha256-2qFgCd0YfNCGkLrf+xvnhQtKjSe8CymMdLlN3svUYTg="
  [mod."golang.org/x/sync"]
    version = "v0.18.0"
    hash = "sha256-S8o6y7GOaYWeq+TzT8BB6T+1mg82Mu08V0TL3ukJprg="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/text"]
    version = "v0.31.0"
    hash = "sha256-AT46RrSmV6+/d5FDhs9fPwYzmQ7WSo+YL9tPfhREwLw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
